import type { RegionPlace } from '../../../types';

// Generated by scripts/build-regions.mjs — do not edit manually.
// State code 31: "Lakshadweep" — lazy chunk.
export const VILLAGES_BY_SUBDISTRICT: Record<number, RegionPlace[]> = {
  5620: [
    [627030, "Amini (CT)"]
  ],
  5621: [
    [627031, "Bitra"]
  ],
  5622: [
    [627032, "Chetlat"]
  ],
  5623: [
    [627033, "Kiltan"]
  ],
  5624: [
    [627034, "Kadmat (CT)"]
  ],
  5625: [
    [627038, "Kavaratti (CT)"],
    [627035, "Pitti (Birds' Island)"],
    [627037, "Suheli Cheriyakara"],
    [627036, "Suheli Valiyakara"]
  ],
  5626: [
    [627044, "Agatti"],
    [627043, "Bangaram"],
    [627045, "Kalpitti"],
    [627040, "Parali (I)"],
    [627041, "Parali (II)"],
    [627042, "Parali (III)"],
    [627039, "Tinnakara"]
  ],
  5627: [
    [627046, "Andrott (CT)"]
  ],
  5628: [
    [627047, "Cheriyam"],
    [627054, "Kalpeni (CT)"],
    [627048, "Kodithala"],
    [627052, "Pitti (I)"],
    [627053, "Pitti (II)"],
    [627049, "Tilakkam (I)"],
    [627050, "Tilakkam (II)"],
    [627051, "Tilakkam (III)"]
  ],
  5629: [
    [627056, "Minicoy (CT)"],
    [627055, "Viringili"]
  ]
};
