import type { RegionPlace } from '../../../types';

// Generated by scripts/build-regions.mjs — do not edit manually.
// State code 7: "Delhi" — lazy chunk.
export const VILLAGES_BY_SUBDISTRICT: Record<number, RegionPlace[]> = {
  430: [
    [63905, "Bankner (CT)"],
    [63920, "Barwala (CT)"],
    [63922, "Bawana (CT)"],
    [63890, "Bazid Pur Thakran"],
    [63906, "Bhor Garh (CT)"],
    [63923, "Darya Pur Kalan (CT)"],
    [63885, "Ghoga"],
    [63886, "Hareoli"],
    [63895, "Holambi Kalan"],
    [63894, "Holambi Khurd"],
    [63893, "Iradat Nagar alias Naya Bans"],
    [63903, "Kankar Khera"],
    [63889, "Katewara"],
    [63919, "Khera Khurd (CT)"],
    [63882, "Kureni"],
    [63866, "Lam Pur"],
    [63867, "Mamoor Pur"],
    [63888, "Mungesh Pur"],
    [63891, "Nangal Thakran"],
    [63887, "Ochandi"],
    [63904, "Pansali"],
    [63918, "Pehlad Pur Bangar (CT)"],
    [63921, "Pooth Khurd (CT)"],
    [63883, "Raja Pur Kalan (Un-inhabited)"],
    [63884, "Sanoth"],
    [63881, "Shah Pur Garhi"],
    [63892, "Sultan Pur Dabas"],
    [63907, "Tikri Khurd (CT)"]
  ],
  431: [
    [63931, "Saoda"]
  ],
  432: [
    [63950, "Bhalswa Jahangir Pur (CT)"],
    [63949, "Shanjar Pur(un-inhabited)"]
  ],
  433: [
    [63952, "Badar Pur Majra Burari"],
    [63957, "Burari (CT)"],
    [63954, "Jagat Pur ilaqa Delhi"],
    [63953, "Jagat Pur ilaqa Shahdara (un-inhabited)"],
    [63958, "Jharoda Majra Burari (CT)"],
    [63956, "Kamal Pur Majra Burari (CT)"],
    [63955, "Mukand Pur (CT)"],
    [63951, "Salem Pur Majra Burari"]
  ],
  436: [
    [63971, "Dayal Pur (CT)"],
    [63967, "Garhi Mendu"],
    [63976, "Khajoori Khas (CT)"],
    [63974, "Khan Pur Dhani (CT)"],
    [63977, "Mir Pur Turk (CT)"],
    [63966, "Sher Pur"],
    [63975, "Tukhmir Pur (CT)"]
  ],
  437: [
    [63980, "Babar Pur (CT)"],
    [63981, "Jaffrabad (CT)"]
  ],
  438: [
    [63982, "Mandoli (CT)"]
  ],
  439: [
    [63983, "Shakar Pur Baramad (CT)"]
  ],
  441: [
    [63985, "Gharonda Neemka Bangar alias Patpar Ganj (CT)"],
    [63984, "Shamas Pur"]
  ],
  448: [
    [63991, "Hastsal (CT)"],
    [63992, "Raja Pur Khurd (CT)"]
  ],
  450: [
    [64002, "Bakkar Wala (CT)"],
    [63995, "Bapraula (CT)"],
    [63994, "Jaffar Pur alias Hiran Kudna"],
    [64001, "Mundka (CT)"],
    [63999, "Nangloi Jat (CT)"],
    [63993, "Neel Wal"],
    [63998, "Nilothi (CT)"],
    [64000, "Quammruddin Nagar (CT)"],
    [63997, "Shafi Pur Ranhola (CT)"],
    [64003, "Tikri Kalan (CT)"],
    [63996, "Tilang Pur Kotla (CT)"]
  ],
  451: [
    [64032, "Badhosra"],
    [64019, "Baqar Garh"],
    [64041, "Dhansa"],
    [64004, "Dichaon Kalan"],
    [64042, "Ghalib Pur"],
    [64020, "Isa Pur"],
    [64047, "Jaffar Pur Kalan (CT)"],
    [64045, "Jharoda Kalan (CT)"],
    [64039, "Jhuljhuli"],
    [64046, "Kair (CT)"],
    [64009, "Kharkhari Nahar"],
    [64050, "Khera (CT)"],
    [64017, "Khera Dabar"],
    [64022, "Malik Pur zer-Najafgarh"],
    [64049, "Mitraon (CT)"],
    [64007, "Mundhela Kalan"],
    [64006, "Mundhela Khurd"],
    [64021, "Qazi Pur"],
    [64012, "Qutab Pur"],
    [64052, "Roshan Pura alias Dichaon Khurd (CT)"],
    [64018, "Samas Pur Khalsa"],
    [64040, "Sarang Pur"],
    [64024, "Sher Pur Deri"],
    [64005, "Surakh Pur"],
    [64008, "Surera"],
    [64048, "Ujwa (CT)"]
  ],
  452: [
    [64055, "Moradabad Pahari (CT)"]
  ],
  453: [
    [64061, "Ghitorni (CT)"],
    [64059, "Kapas Hera (CT)"],
    [64056, "Kusum Pur (CT)"],
    [64057, "Malik Pur Kohi alias Rang Puri (CT)"],
    [64060, "Rajokri (CT)"],
    [64058, "Sambhalka (CT)"]
  ],
  454: [
    [64076, "Deoli (CT)"],
    [64078, "Saidul Azaib (CT)"]
  ],
  455: [
    [64080, "Saidabad (CT)"]
  ],
  456: [
    [64082, "Pul Pehlad (CT)"]
  ],
  6076: [
    [63872, "Akbar Pur Majra"],
    [63910, "Ali Pur (CT)"],
    [63908, "Bakhtawar Pur (CT)"],
    [63909, "Bankauli (CT)"],
    [63902, "Bodh Pur Bija Pur"],
    [63879, "Fateh Pur Jat"],
    [63900, "Garhi Khasru"],
    [63870, "Hamid Pur"],
    [63897, "Hiranki"],
    [63912, "Ibrahim Pur (CT)"],
    [63875, "Jhangola"],
    [63880, "Kham Pur"],
    [63916, "Khera Kalan (CT)"],
    [63914, "Libas Pur (CT)"],
    [63898, "Mohd. Pur Ramzan Pur"],
    [63911, "Mukhmel Pur (CT)"],
    [63901, "Nangli Poona"],
    [63873, "Palla"],
    [63913, "Qadi Pur (CT)"],
    [63874, "Qullak Pur"],
    [63917, "Sahibabad Daulat Pur (CT)"],
    [63869, "Singhola"],
    [63868, "Singhu"],
    [63915, "Siras Pur (CT)"],
    [63877, "Sunger Pur Delhi"],
    [63876, "Sunger Pur Shahdara (un-inhabited)"],
    [63871, "Taj Pur Kalan"],
    [63899, "Tehri Daulat Pur (Un-inhabited)"],
    [63878, "Tigi Pur"],
    [63896, "Zind Pur"]
  ],
  6077: [
    [63946, "Begum Pur (CT)"],
    [63942, "Kirari Suleman Nagar (CT)"],
    [63929, "Madan Pur Dabas"],
    [63941, "Mubarak Pur Dabas (CT)"],
    [63943, "Nithari (CT)"],
    [63947, "Pooth Kalan (CT)"],
    [63940, "Rani Khera (CT)"],
    [63930, "Rasool Pur"],
    [63948, "Sultan Pur Majra (CT)"]
  ],
  6078: [
    [63927, "Budhan Pur"],
    [63928, "Chand Pur"],
    [63932, "Chatesar"],
    [63934, "Garhi Rindhala"],
    [63939, "Gheora (CT)"],
    [63925, "Jat Khor"],
    [63933, "Jonti"],
    [63938, "Kanjhawala (CT)"],
    [63945, "Karala (CT)"],
    [63937, "Lad Pur (CT)"],
    [63944, "Mohammad Pur Majri (CT)"],
    [63935, "Nizam Pur Rashid Pur"],
    [63924, "Punjab Khor"],
    [63936, "Qutab Garh (CT)"],
    [63926, "Salah Pur Majra"]
  ],
  6079: [
    [64070, "Asola (CT)"],
    [64069, "Bhati (CT)"],
    [64073, "Chattar Pur (CT)"],
    [64074, "Maidan Garhi (CT)"],
    [64077, "Neb Sarai (CT)"],
    [64075, "Raj Pur Khurd (CT)"],
    [64063, "Satberi"],
    [64064, "Shahur Pur"],
    [64079, "Tigri (CT)"]
  ],
  6080: [
    [64065, "Aya Nagar (CT)"],
    [64071, "Chandan Hola (CT)"],
    [64068, "Dera Mandi (CT)"],
    [64067, "Fateh Pur Beri (CT)"],
    [64062, "Gadai Pur"],
    [64066, "Jona Pur (CT)"],
    [64072, "Sultan Pur (CT)"]
  ],
  6081: [
    [64086, "Aali (CT)"],
    [64087, "Jait Pur (CT)"],
    [64081, "Kotla Mahigiran (CT)"],
    [64084, "Mithe Pur (CT)"],
    [64085, "Molar Band (CT)"],
    [64083, "Taj Pul (CT)"]
  ],
  6082: [
    [63979, "Gokal Pur (CT)"],
    [63973, "Mustafabad (CT)"],
    [63978, "Ziauddin Pur (CT)"]
  ],
  6083: [
    [63959, "Badar Pur Khadar"],
    [63969, "Baqiabad (CT)"],
    [63965, "Bihari Pur"],
    [63972, "Jiwan Pur alias Johri Pur (CT)"],
    [63970, "Karawal Nagar (CT)"],
    [63960, "Pur Delhi"],
    [63961, "Pur Shahdara"],
    [63962, "Saba Pur Delhi"],
    [63963, "Saba Pur Shahdara"],
    [63968, "Sadat Pur Gujran (CT)"],
    [63964, "Sadat Pur Musalmanan (un-inhabited)"]
  ],
  6084: [
    [63989, "Chilla Saroda Bangar (CT)"],
    [63990, "Chilla Saroda Khadar (CT)"],
    [63988, "Dallo Pura (CT)"],
    [63986, "Gharoli (CT)"],
    [63987, "Kondli (CT)"]
  ],
  6085: [
    [64035, "Asalat Pur Khawad"],
    [64054, "Chhawala (CT)"],
    [64023, "Darya Pur Khurd"],
    [64027, "Daulat Pur"],
    [64044, "Deorala"],
    [64051, "Dindar Pur (CT)"],
    [64011, "Goela Khurd"],
    [64038, "Goman Hera"],
    [64026, "Hasan Pur"],
    [64037, "Jain Pur(Un-inhabited)"],
    [64034, "Jhatikra"],
    [64029, "Kangan Heri"],
    [64016, "Kharkhari Jatmal"],
    [64025, "Kharkhari Rond"],
    [64033, "Nanak Heri"],
    [64010, "Paprawat"],
    [64015, "Pindwala Kalan"],
    [64028, "Pindwala Khurd"],
    [64031, "Raghu Pur"],
    [64043, "Raota"],
    [64014, "Rewla Kham Pur"],
    [64030, "Salah Pur"],
    [64036, "Shikar Pur"],
    [64013, "Taj Pur Khurd"]
  ],
  6086: [
    [64053, "Nangli Sakrawati (CT)"]
  ]
};
