// Generated by scripts/build-regions.mjs — do not edit manually.
// Static import map so Vite/Rollup can safely code-split every village chunk.
// Valid state codes: 35, 28, 12, 18, 10, 4, 22, 7, 30, 24, 6, 2, 1, 20, 29, 32, 37, 31, 23, 27, 14, 17, 15, 13, 21, 34, 3, 8, 11, 33, 36, 38, 16, 9, 5, 19.

export const loadVillageChunk = (
  stateCode: number
): Promise<{ VILLAGES_BY_SUBDISTRICT: Record<number, [number, string][]> }> => {
  switch (stateCode) {
    case 35: return import('./35');
    case 28: return import('./28');
    case 12: return import('./12');
    case 18: return import('./18');
    case 10: return import('./10');
    case 4: return import('./4');
    case 22: return import('./22');
    case 7: return import('./7');
    case 30: return import('./30');
    case 24: return import('./24');
    case 6: return import('./6');
    case 2: return import('./2');
    case 1: return import('./1');
    case 20: return import('./20');
    case 29: return import('./29');
    case 32: return import('./32');
    case 37: return import('./37');
    case 31: return import('./31');
    case 23: return import('./23');
    case 27: return import('./27');
    case 14: return import('./14');
    case 17: return import('./17');
    case 15: return import('./15');
    case 13: return import('./13');
    case 21: return import('./21');
    case 34: return import('./34');
    case 3: return import('./3');
    case 8: return import('./8');
    case 11: return import('./11');
    case 33: return import('./33');
    case 36: return import('./36');
    case 38: return import('./38');
    case 16: return import('./16');
    case 9: return import('./9');
    case 5: return import('./5');
    case 19: return import('./19');
    default:
      return Promise.reject(
        new Error(`No village chunk for state code ${stateCode}`)
      );
  }
};
