// Generated by scripts/build-regions.mjs — do not edit manually.
export const REGIONS_META = {
  generatedAt: "2026-09-12T08:26:41.338Z",
  stateCount: 36,
  districtCount: 784,
  subDistrictCount: 7092,
  blockCount: 7338,
  villageCount: 6871,
  source: {
    hierarchy: 'lgdirectory.gov.in — LGD DWR live endpoints (captcha-free)',
    villages:
      'planemad/india-local-government-directory snapshot merged by LGD village code (LGD DWR does not expose village list endpoints)',
  },
} as const;
