"""
Synthetic Demo Data Generator & Seeder for Chamoli District, Uttarakhand
Clearly labelled as synthetic/demo data for offline testing & research.
"""

from typing import List, Dict, Any
from app.risk_engine import (
    calculate_hazard_score,
    calculate_vulnerability_score,
    calculate_relocation_priority,
    calculate_site_suitability,
    calculate_carrying_capacity,
)

DEMO_USERS = [
    {
        "id": "usr-admin-001",
        "username": "admin",
        "email": "admin@nammasafe.gov.in",
        "hashed_password": "pbkdf2:sha256:admin123",
        "role": "admin",
        "full_name": "Dr. Rajeshwar Semwal",
        "designation": "State Geotechnical Director & GIS Admin",
        "department": "Uttarakhand Disaster Management Authority (USDMA)",
        "assignment": {"state_id": "*", "district_id": "*", "sub_district_id": "*", "area_id": "*"},
    },
    {
        "id": "usr-officer-002",
        "username": "officer",
        "email": "officer@nammasafe.gov.in",
        "hashed_password": "pbkdf2:sha256:officer123",
        "role": "district_officer",
        "full_name": "Smt. Priyanka Bhandari",
        "designation": "District Emergency Operations Officer",
        "department": "District Disaster Management Authority (DDMA Chamoli)",
        "assignment": {"state_id": "uk", "district_id": "chamoli", "sub_district_id": "*", "area_id": "*"},
    },
    {
        "id": "usr-field-003",
        "username": "field",
        "email": "field@nammasafe.gov.in",
        "hashed_password": "pbkdf2:sha256:field123",
        "role": "field_officer",
        "full_name": "Kavita Negi",
        "designation": "Rapid Assessment Field Surveyor",
        "department": "Revenue & Geological Survey Wing, Joshimath",
        "assignment": {"state_id": "uk", "district_id": "chamoli", "sub_district_id": "joshimath", "area_id": "joshimath-central"},
    },
    {
        "id": "usr-citizen-004",
        "username": "citizen",
        "email": "citizen@nammasafe.gov.in",
        "hashed_password": "pbkdf2:sha256:citizen123",
        "role": "normal_citizen",
        "full_name": "Arun Rawat",
        "designation": "Community Liaison & Public Auditor",
        "department": "Civil Defense Uttarakhand",
        "assignment": {"state_id": "uk", "district_id": "chamoli", "sub_district_id": "joshimath", "area_id": "joshimath-central"},
    },
    {
        "id": "usr-local-005",
        "username": "local",
        "email": "local@nammasafe.gov.in",
        "hashed_password": "pbkdf2:sha256:local123",
        "role": "local_office",
        "full_name": "Mahesh Bisht",
        "designation": "Local Relief Accommodation Officer",
        "department": "Joshimath Local Office",
        "assignment": {"state_id": "uk", "district_id": "chamoli", "sub_district_id": "joshimath", "area_id": "joshimath-central"},
    },
    {
        "id": "usr-subdistrict-006",
        "username": "subdistrict",
        "email": "subdistrict@nammasafe.gov.in",
        "hashed_password": "pbkdf2:sha256:subdistrict123",
        "role": "sub_district_officer",
        "full_name": "Neha Rawat",
        "designation": "Joshimath Sub-district Officer",
        "department": "Sub-district Emergency Operations Centre",
        "assignment": {"state_id": "uk", "district_id": "chamoli", "sub_district_id": "joshimath", "area_id": "*"},
    },
    {
        "id": "usr-state-007",
        "username": "state",
        "email": "state@nammasafe.gov.in",
        "hashed_password": "pbkdf2:sha256:state123",
        "role": "state_officer",
        "full_name": "Anita Chauhan",
        "designation": "State Disaster Operations Officer",
        "department": "USDMA",
        "assignment": {"state_id": "uk", "district_id": "*", "sub_district_id": "*", "area_id": "*"},
    },
    {
        "id": "usr-gis-008",
        "username": "gis",
        "email": "gis@nammasafe.gov.in",
        "hashed_password": "pbkdf2:sha256:gis123",
        "role": "gis_analysis_officer",
        "full_name": "Dr. Aditi Joshi",
        "designation": "GIS and Hazard Analysis Officer",
        "department": "USDMA Geospatial Analysis Cell",
        "assignment": {"state_id": "uk", "district_id": "chamoli", "sub_district_id": "*", "area_id": "*"},
    },
]

ADMINISTRATIVE_AREAS = {
    "states": [{"id": "uk", "name": "Uttarakhand"}],
    "districts": [{"id": "chamoli", "state_id": "uk", "name": "Chamoli"}],
    "sub_districts": [{"id": "joshimath", "district_id": "chamoli", "name": "Joshimath"}],
    "areas": [{"id": "joshimath-central", "sub_district_id": "joshimath", "name": "Joshimath Central Division"}],
}

RAW_HABITATIONS = [
    {
        "id": "hab-joshimath",
        "village_code": "VIL-CHM-001",
        "village_name": "Joshimath (Subsidence Sector)",
        "district": "Chamoli",
        "state": "Uttarakhand",
        "population": 16700,
        "households": 3400,
        "children_count": 2800,
        "elderly_count": 2200,
        "hospital_distance_km": 4.5,
        "road_access_score": 45.0,
        "latitude": 30.5574,
        "longitude": 79.5658,
        "landslide_risk": 95.0,
        "flood_risk": 82.0,
        "extreme_rainfall_risk": 88.0,
        "past_disaster_frequency": 90.0,
        "disaster_history_count": 7,
        "notes": "Historic moraine settlement facing severe differential subsidence, widespread structural cracks, and toe erosion from Alaknanda.",
    },
    {
        "id": "hab-raini",
        "village_code": "VIL-CHM-002",
        "village_name": "Raini (Rishiganga Bank)",
        "district": "Chamoli",
        "state": "Uttarakhand",
        "population": 1250,
        "households": 240,
        "children_count": 230,
        "elderly_count": 190,
        "hospital_distance_km": 28.0,
        "road_access_score": 25.0,
        "latitude": 30.4851,
        "longitude": 79.6974,
        "landslide_risk": 94.0,
        "flood_risk": 98.0,
        "extreme_rainfall_risk": 85.0,
        "past_disaster_frequency": 95.0,
        "disaster_history_count": 5,
        "notes": "Chipko movement origin site; direct gorge impact during 2021 glacier lake outburst & debris surge.",
    },
    {
        "id": "hab-tapovan",
        "village_code": "VIL-CHM-003",
        "village_name": "Tapovan (Dhauliganga)",
        "district": "Chamoli",
        "state": "Uttarakhand",
        "population": 2400,
        "households": 480,
        "children_count": 390,
        "elderly_count": 310,
        "hospital_distance_km": 22.0,
        "road_access_score": 35.0,
        "latitude": 30.4950,
        "longitude": 79.6300,
        "landslide_risk": 88.0,
        "flood_risk": 92.0,
        "extreme_rainfall_risk": 84.0,
        "past_disaster_frequency": 85.0,
        "disaster_history_count": 4,
        "notes": "Located below barrage confluence; steep loose scree slopes with recurrent flash flood risk.",
    },
    {
        "id": "hab-helang",
        "village_code": "VIL-CHM-004",
        "village_name": "Helang (Alaknanda Gorge)",
        "district": "Chamoli",
        "state": "Uttarakhand",
        "population": 1800,
        "households": 360,
        "children_count": 280,
        "elderly_count": 220,
        "hospital_distance_km": 14.0,
        "road_access_score": 50.0,
        "latitude": 30.5280,
        "longitude": 79.5100,
        "landslide_risk": 90.0,
        "flood_risk": 75.0,
        "extreme_rainfall_risk": 80.0,
        "past_disaster_frequency": 80.0,
        "disaster_history_count": 4,
        "notes": "Active chronic rockslide zone blocking NH-07 during monsoons; unstable tectonic fault contact.",
    },
    {
        "id": "hab-pandukeshwar",
        "village_code": "VIL-CHM-005",
        "village_name": "Pandukeshwar (Badrinath Route)",
        "district": "Chamoli",
        "state": "Uttarakhand",
        "population": 3100,
        "households": 620,
        "children_count": 450,
        "elderly_count": 410,
        "hospital_distance_km": 19.0,
        "road_access_score": 40.0,
        "latitude": 30.6350,
        "longitude": 79.5550,
        "landslide_risk": 82.0,
        "flood_risk": 86.0,
        "extreme_rainfall_risk": 85.0,
        "past_disaster_frequency": 75.0,
        "disaster_history_count": 3,
        "notes": "Narrow valley funnel; historical inundation during 2013 Kedarnath-Alaknanda deluge.",
    },
    {
        "id": "hab-mana",
        "village_code": "VIL-CHM-006",
        "village_name": "Mana (Frontier High Altitude)",
        "district": "Chamoli",
        "state": "Uttarakhand",
        "population": 1200,
        "households": 240,
        "children_count": 180,
        "elderly_count": 160,
        "hospital_distance_km": 36.0,
        "road_access_score": 30.0,
        "latitude": 30.7680,
        "longitude": 79.4950,
        "landslide_risk": 78.0,
        "flood_risk": 70.0,
        "extreme_rainfall_risk": 90.0,
        "past_disaster_frequency": 70.0,
        "disaster_history_count": 2,
        "notes": "First Indian frontier habitation at 3,200m; extreme winter avalanche corridors & moraine slides.",
    },
    {
        "id": "hab-pipalkoti",
        "village_code": "VIL-CHM-007",
        "village_name": "Pipalkoti (Middle Valley)",
        "district": "Chamoli",
        "state": "Uttarakhand",
        "population": 4500,
        "households": 900,
        "children_count": 650,
        "elderly_count": 550,
        "hospital_distance_km": 16.0,
        "road_access_score": 75.0,
        "latitude": 30.4300,
        "longitude": 79.4300,
        "landslide_risk": 68.0,
        "flood_risk": 65.0,
        "extreme_rainfall_risk": 60.0,
        "past_disaster_frequency": 60.0,
        "disaster_history_count": 3,
        "notes": "Valley transit hub experiencing riverbank toe undercutting and periodic road subsidence.",
    },
    {
        "id": "hab-ghat",
        "village_code": "VIL-CHM-008",
        "village_name": "Ghat (Nandakini Valley)",
        "district": "Chamoli",
        "state": "Uttarakhand",
        "population": 2800,
        "households": 560,
        "children_count": 420,
        "elderly_count": 380,
        "hospital_distance_km": 24.0,
        "road_access_score": 45.0,
        "latitude": 30.2600,
        "longitude": 79.4800,
        "landslide_risk": 85.0,
        "flood_risk": 88.0,
        "extreme_rainfall_risk": 92.0,
        "past_disaster_frequency": 80.0,
        "disaster_history_count": 4,
        "notes": "Cloudburst epicenter with high sediment debris flow across residential bazaar.",
    },
    {
        "id": "hab-urgam",
        "village_code": "VIL-CHM-009",
        "village_name": "Urgam (Kalpeshwar Valley)",
        "district": "Chamoli",
        "state": "Uttarakhand",
        "population": 1950,
        "households": 390,
        "children_count": 300,
        "elderly_count": 260,
        "hospital_distance_km": 32.0,
        "road_access_score": 28.0,
        "latitude": 30.5600,
        "longitude": 79.4400,
        "landslide_risk": 74.0,
        "flood_risk": 60.0,
        "extreme_rainfall_risk": 75.0,
        "past_disaster_frequency": 55.0,
        "disaster_history_count": 2,
        "notes": "Steep valley accessible only by single unpaved rural road prone to cutoff.",
    },
    {
        "id": "hab-tharali",
        "village_code": "VIL-CHM-010",
        "village_name": "Tharali (Pindar Valley)",
        "district": "Chamoli",
        "state": "Uttarakhand",
        "population": 3600,
        "households": 720,
        "children_count": 520,
        "elderly_count": 460,
        "hospital_distance_km": 26.0,
        "road_access_score": 55.0,
        "latitude": 30.0750,
        "longitude": 79.5050,
        "landslide_risk": 70.0,
        "flood_risk": 85.0,
        "extreme_rainfall_risk": 82.0,
        "past_disaster_frequency": 75.0,
        "disaster_history_count": 3,
        "notes": "Prone to severe Pindar river seasonal swell and flash flooding during monsoon peaks.",
    },
]

RAW_RELOCATION_SITES = [
    {
        "id": "site-gauchar-01",
        "site_name": "Gauchar Plateau Safe Enclave",
        "district": "Chamoli",
        "land_area_acres": 48.0,
        "estimated_capacity": 650, # families
        "current_occupancy_families": 45,
        "water_score": 92.0,
        "road_score": 95.0,
        "school_score": 90.0,
        "hospital_score": 88.0,
        "low_hazard_score": 94.0,
        "flat_land_score": 92.0,
        "latitude": 30.2900,
        "longitude": 79.1550,
        "land_capacity_families": 700,
        "water_capacity_families": 650,
        "school_capacity_families": 600,
        "health_capacity_families": 620,
        "road_capacity_families": 750,
    },
    {
        "id": "site-gwaldam-02",
        "site_name": "Gwaldam Hill Terrace Reserve",
        "district": "Chamoli",
        "land_area_acres": 34.0,
        "estimated_capacity": 420,
        "current_occupancy_families": 30,
        "water_score": 84.0,
        "road_score": 82.0,
        "school_score": 80.0,
        "hospital_score": 75.0,
        "low_hazard_score": 88.0,
        "flat_land_score": 80.0,
        "latitude": 30.0150,
        "longitude": 79.5600,
        "land_capacity_families": 500,
        "water_capacity_families": 420,
        "school_capacity_families": 450,
        "health_capacity_families": 430,
        "road_capacity_families": 480,
    },
    {
        "id": "site-karanprayag-03",
        "site_name": "Karnaprayag Upper Ridge Township",
        "district": "Chamoli",
        "land_area_acres": 28.5,
        "estimated_capacity": 380,
        "current_occupancy_families": 20,
        "water_score": 88.0,
        "road_score": 90.0,
        "school_score": 85.0,
        "hospital_score": 92.0,
        "low_hazard_score": 85.0,
        "flat_land_score": 78.0,
        "latitude": 30.2650,
        "longitude": 79.2250,
        "land_capacity_families": 420,
        "water_capacity_families": 400,
        "school_capacity_families": 380,
        "health_capacity_families": 450,
        "road_capacity_families": 500,
    },
    {
        "id": "site-nandprayag-04",
        "site_name": "Nandprayag Plateau Buffer",
        "district": "Chamoli",
        "land_area_acres": 22.0,
        "estimated_capacity": 290,
        "current_occupancy_families": 15,
        "water_score": 86.0,
        "road_score": 84.0,
        "school_score": 78.0,
        "hospital_score": 80.0,
        "low_hazard_score": 89.0,
        "flat_land_score": 82.0,
        "latitude": 30.3350,
        "longitude": 79.3150,
        "land_capacity_families": 330,
        "water_capacity_families": 310,
        "school_capacity_families": 290,
        "health_capacity_families": 320,
        "road_capacity_families": 350,
    },
]

RAW_RED_ZONES = [
    {
        "id": "rz-joshimath-sub",
        "zone_name": "Joshimath Moraine Subsidence Red Zone",
        "hazard_type": "Land Subsidence",
        "risk_level": "Critical",
        "hazard_score": 94.5,
        "data_source": "Wadia Institute of Himalayan Geology & ISRO Bhuvan InSAR",
        "last_updated": "2025-06-15",
        "zone_geometry": {
            "type": "Polygon",
            "coordinates": [
                [
                    [79.545, 30.540],
                    [79.585, 30.540],
                    [79.595, 30.575],
                    [79.555, 30.585],
                    [79.535, 30.560],
                    [79.545, 30.540],
                ]
            ],
        },
    },
    {
        "id": "rz-rishiganga-flood",
        "zone_name": "Rishiganga-Dhauliganga Debris & Flood Plain",
        "hazard_type": "Flash Flood",
        "risk_level": "Critical",
        "hazard_score": 96.0,
        "data_source": "Central Water Commission & NASA GPM Rainfall Sentinel",
        "last_updated": "2025-07-10",
        "zone_geometry": {
            "type": "Polygon",
            "coordinates": [
                [
                    [79.610, 30.470],
                    [79.720, 30.460],
                    [79.730, 30.510],
                    [79.620, 30.520],
                    [79.610, 30.470],
                ]
            ],
        },
    },
    {
        "id": "rz-helang-landslide",
        "zone_name": "Helang-Marwari Active Rockslide Corridor",
        "hazard_type": "Landslide",
        "risk_level": "High",
        "hazard_score": 88.0,
        "data_source": "Geological Survey of India (GSI) Landslide Susceptibility",
        "last_updated": "2025-05-20",
        "zone_geometry": {
            "type": "Polygon",
            "coordinates": [
                [
                    [79.490, 30.510],
                    [79.530, 30.515],
                    [79.540, 30.545],
                    [79.500, 30.540],
                    [79.490, 30.510],
                ]
            ],
        },
    },
    {
        "id": "rz-nandakini-cloudburst",
        "zone_name": "Ghat-Nandakini Cloudburst Danger Zone",
        "hazard_type": "Cloudburst",
        "risk_level": "High",
        "hazard_score": 86.5,
        "data_source": "State Disaster Management Authority Weather Radar",
        "last_updated": "2025-08-01",
        "zone_geometry": {
            "type": "Polygon",
            "coordinates": [
                [
                    [79.450, 30.240],
                    [79.520, 30.245],
                    [79.530, 30.285],
                    [79.460, 30.280],
                    [79.450, 30.240],
                ]
            ],
        },
    },
    {
        "id": "rz-pindar-inundation",
        "zone_name": "Pindar River Seasonal Flash Surge Basin",
        "hazard_type": "Flash Flood",
        "risk_level": "High",
        "hazard_score": 79.0,
        "data_source": "Uttarakhand Irrigation Dept Flood Hazard Atlas",
        "last_updated": "2025-06-30",
        "zone_geometry": {
            "type": "Polygon",
            "coordinates": [
                [
                    [79.480, 30.050],
                    [79.540, 30.060],
                    [79.530, 30.100],
                    [79.470, 30.090],
                    [79.480, 30.050],
                ]
            ],
        },
    },
]

RAW_DISASTER_EVENTS = [
    {"id": "ev-01", "habitation_id": "hab-joshimath", "hazard_type": "Land Subsidence", "event_date": "2023-01-03", "intensity": "Severe (1.8 cm/day crack widening)", "severity_level": "Critical", "affected_people": 4200, "houses_damaged": 860, "deaths": 0, "source_url": "https://usdma.uk.gov.in/reports/joshimath-2023"},
    {"id": "ev-02", "habitation_id": "hab-joshimath", "hazard_type": "Land Subsidence", "event_date": "2024-07-18", "intensity": "Monsoon Toe Seepage Surge", "severity_level": "High", "affected_people": 1500, "houses_damaged": 120, "deaths": 0, "source_url": "https://usdma.uk.gov.in/bulletin-2024"},
    {"id": "ev-03", "habitation_id": "hab-raini", "hazard_type": "Flash Flood", "event_date": "2021-02-07", "intensity": "Glacier Rock-Ice Avalanche Surge (Rishiganga)", "severity_level": "Critical", "affected_people": 850, "houses_damaged": 45, "deaths": 204, "source_url": "https://wadia.res.in/chamoli-flood-2021"},
    {"id": "ev-04", "habitation_id": "hab-raini", "hazard_type": "Landslide", "event_date": "2022-06-12", "intensity": "Bridge Abutment Scour & Slope Failure", "severity_level": "High", "affected_people": 400, "houses_damaged": 14, "deaths": 0, "source_url": "https://gsi.gov.in/landslide-portal"},
    {"id": "ev-05", "habitation_id": "hab-tapovan", "hazard_type": "Flash Flood", "event_date": "2021-02-07", "intensity": "Hydro Project Tunnel Inundation", "severity_level": "Critical", "affected_people": 1800, "houses_damaged": 60, "deaths": 140, "source_url": "https://nidm.gov.in/tapovan-study"},
    {"id": "ev-06", "habitation_id": "hab-tapovan", "hazard_type": "Landslide", "event_date": "2023-08-14", "intensity": "Debris Avalanche on Access Road", "severity_level": "High", "affected_people": 650, "houses_damaged": 18, "deaths": 2, "source_url": "https://chamoli.nic.in/disaster"},
    {"id": "ev-07", "habitation_id": "hab-helang", "hazard_type": "Landslide", "event_date": "2023-08-15", "intensity": "Major Slope Slump Over NH-07", "severity_level": "High", "affected_people": 900, "houses_damaged": 22, "deaths": 1, "source_url": "https://nhai.org.in/corridor-status"},
    {"id": "ev-08", "habitation_id": "hab-helang", "hazard_type": "Landslide", "event_date": "2024-08-02", "intensity": "Continuous Hill Collapse", "severity_level": "High", "affected_people": 450, "houses_damaged": 8, "deaths": 0, "source_url": "https://ddma-chamoli.in/incidents"},
    {"id": "ev-09", "habitation_id": "hab-pandukeshwar", "hazard_type": "Flash Flood", "event_date": "2013-06-17", "intensity": "Himalayan Cloudburst Deluge", "severity_level": "Critical", "affected_people": 2200, "houses_damaged": 95, "deaths": 18, "source_url": "https://ndma.gov.in/uttarakhand-2013"},
    {"id": "ev-10", "habitation_id": "hab-pandukeshwar", "hazard_type": "Avalanche", "event_date": "2022-03-04", "intensity": "Upper Ridge Snow Slab Release", "severity_level": "Medium", "affected_people": 300, "houses_damaged": 5, "deaths": 0, "source_url": "https://sase.drdo.in/avalanches"},
    {"id": "ev-11", "habitation_id": "hab-mana", "hazard_type": "Rockfall", "event_date": "2023-05-19", "intensity": "Permafrost Thaw Boulder Detachment", "severity_level": "Medium", "affected_people": 200, "houses_damaged": 6, "deaths": 0, "source_url": "https://usdma.uk.gov.in/mana"},
    {"id": "ev-12", "habitation_id": "hab-mana", "hazard_type": "Avalanche", "event_date": "2024-02-14", "intensity": "High Altitude Powder Avalanche", "severity_level": "Medium", "affected_people": 150, "houses_damaged": 4, "deaths": 0, "source_url": "https://ddma-chamoli.in/mana-aval"},
    {"id": "ev-13", "habitation_id": "hab-pipalkoti", "hazard_type": "Landslide", "event_date": "2023-07-28", "intensity": "Valley Edge Subsidence & Retaining Wall Crash", "severity_level": "Medium", "affected_people": 600, "houses_damaged": 12, "deaths": 0, "source_url": "https://pwd.uk.gov.in/pipalkoti"},
    {"id": "ev-14", "habitation_id": "hab-pipalkoti", "hazard_type": "Flash Flood", "event_date": "2024-07-09", "intensity": "Alaknanda Flood High Water Mark", "severity_level": "Medium", "affected_people": 450, "houses_damaged": 9, "deaths": 0, "source_url": "https://cwc.gov.in/river-basin"},
    {"id": "ev-15", "habitation_id": "hab-ghat", "hazard_type": "Cloudburst", "event_date": "2019-08-12", "intensity": "Localised Cloudburst (180 mm/hr)", "severity_level": "Critical", "affected_people": 1400, "houses_damaged": 48, "deaths": 6, "source_url": "https://imd.gov.in/cloudburst-archives"},
    {"id": "ev-16", "habitation_id": "hab-ghat", "hazard_type": "Flash Flood", "event_date": "2021-09-02", "intensity": "Nandakini Overflow Debris Sweep", "severity_level": "High", "affected_people": 850, "houses_damaged": 26, "deaths": 2, "source_url": "https://chamoli.nic.in/ghat-flood"},
    {"id": "ev-17", "habitation_id": "hab-urgam", "hazard_type": "Landslide", "event_date": "2022-08-19", "intensity": "Village Access Cutoff for 14 Days", "severity_level": "Medium", "affected_people": 1100, "houses_damaged": 8, "deaths": 0, "source_url": "https://ddma-chamoli.in/urgam-isolation"},
    {"id": "ev-18", "habitation_id": "hab-urgam", "hazard_type": "Extreme Rainfall", "event_date": "2024-08-10", "intensity": "Sustained Monsoonal Deluge (240 mm in 24 hrs)", "severity_level": "Medium", "affected_people": 450, "houses_damaged": 4, "deaths": 0, "source_url": "https://imd.gov.in/rainfall-report"},
    {"id": "ev-19", "habitation_id": "hab-tharali", "hazard_type": "Flash Flood", "event_date": "2023-08-19", "intensity": "Pindar River Breached Low Banks", "severity_level": "High", "affected_people": 1300, "houses_damaged": 34, "deaths": 1, "source_url": "https://usdma.uk.gov.in/tharali-flood"},
    {"id": "ev-20", "habitation_id": "hab-tharali", "hazard_type": "Landslide", "event_date": "2024-07-22", "intensity": "Slope Toe Collapse Along Karnaprayag-Gwaldam Road", "severity_level": "Medium", "affected_people": 500, "houses_damaged": 10, "deaths": 0, "source_url": "https://bro.gov.in/road-clearance"},
    {"id": "ev-21", "habitation_id": "hab-joshimath", "hazard_type": "Landslide", "event_date": "2021-10-18", "intensity": "Heavy Unseasonal Rain Induced Slip", "severity_level": "High", "affected_people": 900, "houses_damaged": 35, "deaths": 0, "source_url": "https://usdma.uk.gov.in/oct-2021"},
    {"id": "ev-22", "habitation_id": "hab-raini", "hazard_type": "Extreme Rainfall", "event_date": "2023-07-15", "intensity": "Torrential Downpour Triggering Mudflows", "severity_level": "High", "affected_people": 500, "houses_damaged": 12, "deaths": 0, "source_url": "https://ddma-chamoli.in/raini-2023"},
]

RAW_FIELD_REPORTS = [
    {
        "id": "fr-001",
        "habitation_id": "hab-joshimath",
        "officer_id": "usr-field-003",
        "officer_name": "Kavita Negi (Field Surveyor)",
        "report_type": "Crack Formation & Differential Settlement",
        "description": "Inspected Sunil Ward: 4 new transversal ground fissures measuring 4.5cm width identified across 12 concrete residential slabs. Water seepage detected at foundation toe.",
        "image_url": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80",
        "reported_at": "2025-08-25T10:30:00Z",
        "verified": True,
        "severity": "Critical",
        "latitude": 30.5590,
        "longitude": 79.5630,
    },
    {
        "id": "fr-002",
        "habitation_id": "hab-raini",
        "officer_id": "usr-field-003",
        "officer_name": "Kavita Negi (Field Surveyor)",
        "report_type": "Gorge Bank Erosion & Slope Slump",
        "description": "Rishiganga river water level rose 1.8m post afternoon rain. Unconsolidated riverbank gravel washed away near lower primary school boundary.",
        "image_url": "https://images.unsplash.com/photo-1518457607834-6e8d80c183c5?auto=format&fit=crop&w=600&q=80",
        "reported_at": "2025-08-26T14:15:00Z",
        "verified": True,
        "severity": "High",
        "latitude": 30.4860,
        "longitude": 79.6960,
    },
    {
        "id": "fr-003",
        "habitation_id": "hab-helang",
        "officer_id": "usr-field-003",
        "officer_name": "Kavita Negi (Field Surveyor)",
        "report_type": "Active Rockfall & Road Barrier Impact",
        "description": "Periodic shooting stones noted on NH-07 Km 486. Debris clearance ongoing with BRO excavator. Commuters halted temporarily.",
        "image_url": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
        "reported_at": "2025-08-27T08:45:00Z",
        "verified": False,
        "severity": "High",
        "latitude": 30.5290,
        "longitude": 79.5080,
    },
    {
        "id": "fr-004",
        "habitation_id": "hab-ghat",
        "officer_id": "usr-field-003",
        "officer_name": "Kavita Negi (Field Surveyor)",
        "report_type": "Nandakini Siltation & Storm Drain Clogging",
        "description": "High mud turbidity in drainage channels. 3 shops in main market inundated by runoff gravel. Local administration alert sounded.",
        "image_url": "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=600&q=80",
        "reported_at": "2025-08-28T09:00:00Z",
        "verified": True,
        "severity": "High",
        "latitude": 30.2620,
        "longitude": 79.4790,
    },
    {
        "id": "fr-005",
        "habitation_id": "hab-urgam",
        "officer_id": "usr-field-003",
        "officer_name": "Kavita Negi (Field Surveyor)",
        "report_type": "Rural Culvert Collapse",
        "description": "Secondary rural bridge connecting upper Urgam hamlet damaged by flash runoff. Pedestrian detour established through village footpath.",
        "image_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80",
        "reported_at": "2025-08-28T16:20:00Z",
        "verified": False,
        "severity": "Medium",
        "latitude": 30.5580,
        "longitude": 79.4380,
    },
]

INFRASTRUCTURE_DATA = [
    {"id": "inf-hosp-01", "name": "District Hospital Gopeshwar / Chamoli", "type": "hospital", "latitude": 30.4120, "longitude": 79.3280, "capacity_or_type": "200 Beds - Level 2 Trauma"},
    {"id": "inf-hosp-02", "name": "Community Health Center Joshimath", "type": "hospital", "latitude": 30.5540, "longitude": 79.5620, "capacity_or_type": "50 Beds - Emergency Stabilisation"},
    {"id": "inf-hosp-03", "name": "Sub-District Hospital Karnaprayag", "type": "hospital", "latitude": 30.2620, "longitude": 79.2210, "capacity_or_type": "80 Beds - General Surgery"},
    {"id": "inf-hosp-04", "name": "CHC Gauchar Base Clinic", "type": "hospital", "latitude": 30.2920, "longitude": 79.1580, "capacity_or_type": "40 Beds - Disaster Relief Outpost"},
    {"id": "inf-sch-01", "name": "Kendriya Vidyalaya Joshimath", "type": "school", "latitude": 30.5520, "longitude": 79.5690, "capacity_or_type": "Emergency Shelter Capacity: 600"},
    {"id": "inf-sch-02", "name": "Govt Inter College Gauchar", "type": "school", "latitude": 30.2890, "longitude": 79.1520, "capacity_or_type": "Hostel Complex: 800 Evacuees"},
    {"id": "inf-sch-03", "name": "GIC Karnaprayag Campus", "type": "school", "latitude": 30.2640, "longitude": 79.2280, "capacity_or_type": "Shelter Capacity: 500"},
    {"id": "inf-road-01", "name": "NH-07 Rishikesh-Badrinath Evacuation Corridor", "type": "evacuation_road", "latitude": 30.4000, "longitude": 79.3300, "capacity_or_type": "All-Weather 2-Lane Highway"},
    {"id": "inf-road-02", "name": "Karnaprayag-Gwaldam Highway Route", "type": "evacuation_road", "latitude": 30.1500, "longitude": 79.3900, "capacity_or_type": "Alternative Southern Egress"},
]

def get_processed_seed_data() -> Dict[str, Any]:
    """Processes raw records through mathematical risk formulas and returns fully linked data."""
    
    # 1. Process Habitations
    habitations = []
    for raw in RAW_HABITATIONS:
        h_score = calculate_hazard_score(
            landslide_risk=raw["landslide_risk"],
            flood_risk=raw["flood_risk"],
            extreme_rainfall_risk=raw["extreme_rainfall_risk"],
            past_disaster_frequency=raw["past_disaster_frequency"],
        )
        v_score = calculate_vulnerability_score(
            population=raw["population"],
            households=raw["households"],
            children_count=raw["children_count"],
            elderly_count=raw["elderly_count"],
            hospital_distance_km=raw["hospital_distance_km"],
            road_access_score=raw["road_access_score"],
        )
        disaster_hist_score = min(100.0, raw["disaster_history_count"] * 16.0)
        p_score, p_level = calculate_relocation_priority(
            hazard_score=h_score,
            vulnerability_score=v_score,
            disaster_history_score=disaster_hist_score,
        )
        
        hab = {
            **raw,
            "hazard_score": h_score,
            "vulnerability_score": v_score,
            "priority_score": p_score,
            "priority_level": p_level,
            "location_geojson": {
                "type": "Point",
                "coordinates": [raw["longitude"], raw["latitude"]],
            },
        }
        habitations.append(hab)

    # 2. Process Relocation Sites
    relocation_sites = []
    for raw in RAW_RELOCATION_SITES:
        suitability = calculate_site_suitability(
            low_hazard_score=raw["low_hazard_score"],
            flat_land_score=raw["flat_land_score"],
            road_score=raw["road_score"],
            water_score=raw["water_score"],
            school_score=raw["school_score"],
            hospital_score=raw["hospital_score"],
        )
        final_cap = calculate_carrying_capacity(
            land_capacity=raw["land_capacity_families"],
            water_capacity=raw["water_capacity_families"],
            school_capacity=raw["school_capacity_families"],
            health_capacity=raw["health_capacity_families"],
            road_capacity=raw["road_capacity_families"],
        )
        avail_cap = max(0, final_cap - raw["current_occupancy_families"])
        
        site = {
            **raw,
            "suitability_score": suitability,
            "final_capacity_families": final_cap,
            "available_capacity_families": avail_cap,
            "location_geojson": {
                "type": "Point",
                "coordinates": [raw["longitude"], raw["latitude"]],
            },
        }
        relocation_sites.append(site)

    # 3. Generate Relocation Recommendations
    # Match high-priority habitations to most suitable safe sites
    recommendations = []
    sorted_habs = sorted(habitations, key=lambda x: x["priority_score"], reverse=True)
    
    # Preferred mapping for pilot
    site_map = {
        "hab-joshimath": ("site-gauchar-01", 350, "Approved"),
        "hab-raini": ("site-nandprayag-04", 120, "Approved"),
        "hab-tapovan": ("site-karanprayag-03", 180, "Under Review"),
        "hab-helang": ("site-karanprayag-03", 140, "Under Review"),
        "hab-ghat": ("site-gwaldam-02", 150, "Draft"),
        "hab-pandukeshwar": ("site-gauchar-01", 160, "Draft"),
        "hab-tharali": ("site-gwaldam-02", 110, "Draft"),
        "hab-urgam": ("site-nandprayag-04", 90, "Draft"),
        "hab-pipalkoti": ("site-gauchar-01", 100, "Draft"),
        "hab-mana": ("site-karanprayag-03", 60, "Draft"),
    }

    sites_by_id = {s["id"]: s for s in relocation_sites}
    for idx, h in enumerate(sorted_habs):
        pref_site_id, fams, status = site_map.get(h["id"], ("site-gauchar-01", 100, "Draft"))
        target_s = sites_by_id.get(pref_site_id, relocation_sites[0])
        
        # Risk reduction calculation
        residual_risk = max(5.0, (100.0 - target_s["suitability_score"]) * 0.4)
        risk_red = round(max(60.0, min(95.0, ((h["priority_score"] - residual_risk) / h["priority_score"]) * 100.0)), 1)
        
        rec = {
            "id": f"rec-{idx+1:03d}",
            "habitation_id": h["id"],
            "habitation_name": h["village_name"],
            "relocation_site_id": target_s["id"],
            "relocation_site_name": target_s["site_name"],
            "hazard_score": h["hazard_score"],
            "vulnerability_score": h["vulnerability_score"],
            "disaster_history_score": min(100.0, h["disaster_history_count"] * 16.0),
            "final_priority_score": h["priority_score"],
            "priority_level": h["priority_level"],
            "recommended_families": fams,
            "risk_reduction_percent": risk_red,
            "explanation": (
                f"Multi-hazard assessment in {h['village_name']} indicated composite risk score {h['priority_score']} "
                f"({h['priority_level']}). Shifting {fams} vulnerable households to {target_s['site_name']} "
                f"(Suitability index: {target_s['suitability_score']}/100) lowers hazard exposure by {risk_red}%. "
                f"Site verified for adequate water, access road, and public health service buffers."
            ),
            "status": status,
            "created_at": "2025-08-20T09:00:00Z",
        }
        recommendations.append(rec)

    return {
        "users": DEMO_USERS,
        "administrative_areas": ADMINISTRATIVE_AREAS,
        "risk_alerts": [],
        "user_sessions": [],
        "audit_events": [],
        "habitations": habitations,
        "relocation_sites": relocation_sites,
        "red_zones": RAW_RED_ZONES,
        "hazard_events": RAW_DISASTER_EVENTS,
        "recommendations": recommendations,
        "field_reports": RAW_FIELD_REPORTS,
        "infrastructure": INFRASTRUCTURE_DATA,
    }
